package dev.doctor4t.trainmurdermystery.datagen;

import dev.doctor4t.trainmurdermystery.index.TrainMurderMysteryBlocks;
import dev.doctor4t.trainmurdermystery.index.TrainMurderMysteryEntities;
import dev.doctor4t.trainmurdermystery.index.TrainMurderMysteryItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.data.client.Models;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class TrainMurderMysteryLangGen extends FabricLanguageProvider {

    public TrainMurderMysteryLangGen(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup wrapperLookup, TranslationBuilder builder) {
        builder.add(TrainMurderMysteryEntities.SEAT, "Seat");

        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_VENT_SHAFT, "Stainless Steel Vent Shaft");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_VENT_HATCH, "Stainless Steel Vent Hatch");
        builder.add(TrainMurderMysteryBlocks.DARK_STEEL_VENT_SHAFT, "Dark Steel Vent Shaft");
        builder.add(TrainMurderMysteryBlocks.DARK_STEEL_VENT_HATCH, "Dark Steel Vent Hatch");
        builder.add(TrainMurderMysteryBlocks.TARNISHED_GOLD_VENT_SHAFT, "Tarnished Gold Vent Shaft");
        builder.add(TrainMurderMysteryBlocks.TARNISHED_GOLD_VENT_HATCH, "Tarnished Gold Vent Hatch");
        builder.add(TrainMurderMysteryBlocks.TARNISHED_GOLD, "Tarnished Gold");
        builder.add(TrainMurderMysteryBlocks.TARNISHED_GOLD_STAIRS, "Tarnished Gold Stairs");
        builder.add(TrainMurderMysteryBlocks.TARNISHED_GOLD_SLAB, "Tarnished Gold Slab");
        builder.add(TrainMurderMysteryBlocks.TARNISHED_GOLD_WALL, "Tarnished Gold Wall");
        builder.add(TrainMurderMysteryBlocks.TARNISHED_GOLD_PILLAR, "Tarnished Gold Pillar");
        builder.add(TrainMurderMysteryBlocks.GOLD, "Gold");
        builder.add(TrainMurderMysteryBlocks.GOLD_STAIRS, "Gold Stairs");
        builder.add(TrainMurderMysteryBlocks.GOLD_SLAB, "Gold Slab");
        builder.add(TrainMurderMysteryBlocks.GOLD_WALL, "Gold Wall");
        builder.add(TrainMurderMysteryBlocks.GOLD_PILLAR, "Gold Pillar");
        builder.add(TrainMurderMysteryBlocks.PRISTINE_GOLD, "Pristine Gold");
        builder.add(TrainMurderMysteryBlocks.PRISTINE_GOLD_STAIRS, "Pristine Gold Stairs");
        builder.add(TrainMurderMysteryBlocks.PRISTINE_GOLD_SLAB, "Pristine Gold Slab");
        builder.add(TrainMurderMysteryBlocks.PRISTINE_GOLD_WALL, "Pristine Gold Wall");
        builder.add(TrainMurderMysteryBlocks.PRISTINE_GOLD_PILLAR, "Pristine Gold Pillar");
        builder.add(TrainMurderMysteryBlocks.METAL_SHEET, "Metal Sheet");
        builder.add(TrainMurderMysteryBlocks.METAL_SHEET_STAIRS, "Metal Sheet Stairs");
        builder.add(TrainMurderMysteryBlocks.METAL_SHEET_SLAB, "Metal Sheet Slab");
        builder.add(TrainMurderMysteryBlocks.METAL_SHEET_WALL, "Metal Sheet Wall");
        builder.add(TrainMurderMysteryBlocks.METAL_SHEET_DOOR, "Metal Sheet Door");
        builder.add(TrainMurderMysteryBlocks.COCKPIT_DOOR, "Cockpit Door");
        builder.add(TrainMurderMysteryBlocks.METAL_SHEET_WALKWAY, "Metal Sheet Walkway");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_LADDER, "Stainless Steel Ladder");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL, "Stainless Steel");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_STAIRS, "Stainless Steel Stairs");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_SLAB, "Stainless Steel Slab");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_WALL, "Stainless Steel Wall");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_WALKWAY, "Stainless Steel Walkway");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_PILLAR, "Stainless Steel Pillar");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_BRANCH, "Stainless Steel Branch");
        builder.add(TrainMurderMysteryBlocks.DARK_STEEL, "Dark Steel");
        builder.add(TrainMurderMysteryBlocks.DARK_STEEL_STAIRS, "Dark Steel Stairs");
        builder.add(TrainMurderMysteryBlocks.DARK_STEEL_SLAB, "Dark Steel Slab");
        builder.add(TrainMurderMysteryBlocks.DARK_STEEL_WALL, "Dark Steel Wall");
        builder.add(TrainMurderMysteryBlocks.DARK_STEEL_WALKWAY, "Dark Steel Walkway");
        builder.add(TrainMurderMysteryBlocks.DARK_STEEL_PILLAR, "Dark Steel Pillar");
        builder.add(TrainMurderMysteryBlocks.DARK_STEEL_BRANCH, "Dark Steel Branch");
        builder.add(TrainMurderMysteryBlocks.RHOMBUS_GLASS, "Rhombus Glass");
        builder.add(TrainMurderMysteryBlocks.HULL_GLASS, "Hull Glass");
        builder.add(TrainMurderMysteryBlocks.RHOMBUS_HULL_GLASS, "Rhombus Hull Glass");
        builder.add(TrainMurderMysteryBlocks.GOLDEN_GLASS_PANEL, "Golden Glass Panel");
        builder.add(TrainMurderMysteryBlocks.CULLING_GLASS, "Culling Glass");
        builder.add(TrainMurderMysteryBlocks.PRIVACY_GLASS_PANEL, "Privacy Glass");
        builder.add(TrainMurderMysteryBlocks.MARBLE, "Marble");
        builder.add(TrainMurderMysteryBlocks.MARBLE_STAIRS, "Marble Stairs");
        builder.add(TrainMurderMysteryBlocks.MARBLE_SLAB, "Marble Slab");
        builder.add(TrainMurderMysteryBlocks.MARBLE_WALL, "Marble Wall");
        builder.add(TrainMurderMysteryBlocks.MARBLE_TILES, "Marble Tiles");
        builder.add(TrainMurderMysteryBlocks.MARBLE_TILE_STAIRS, "Marble Tile Stairs");
        builder.add(TrainMurderMysteryBlocks.MARBLE_TILE_SLAB, "Marble Tile Slab");
        builder.add(TrainMurderMysteryBlocks.MARBLE_TILE_WALL, "Marble Tile Wall");
        builder.add(TrainMurderMysteryBlocks.DARK_MARBLE, "Dark Marble");
        builder.add(TrainMurderMysteryBlocks.DARK_MARBLE_STAIRS, "Dark Marble Stairs");
        builder.add(TrainMurderMysteryBlocks.DARK_MARBLE_SLAB, "Dark Marble Slab");
        builder.add(TrainMurderMysteryBlocks.DARK_MARBLE_WALL, "Dark Marble Wall");
        builder.add(TrainMurderMysteryBlocks.MARBLE_MOSAIC, "Marble Mosaic");
        builder.add(TrainMurderMysteryBlocks.WHITE_HULL, "White Hull");
        builder.add(TrainMurderMysteryBlocks.WHITE_HULL_STAIRS, "White Hull Stairs");
        builder.add(TrainMurderMysteryBlocks.WHITE_HULL_SLAB, "White Hull Slab");
        builder.add(TrainMurderMysteryBlocks.WHITE_HULL_WALL, "White Hull Wall");
        builder.add(TrainMurderMysteryBlocks.CULLING_WHITE_HULL, "Culling White Hull");
        builder.add(TrainMurderMysteryBlocks.BLACK_HULL, "Black Hull");
        builder.add(TrainMurderMysteryBlocks.BLACK_HULL_STAIRS, "Black Hull Stairs");
        builder.add(TrainMurderMysteryBlocks.BLACK_HULL_SLAB, "Black Hull Slab");
        builder.add(TrainMurderMysteryBlocks.BLACK_HULL_WALL, "Black Hull Wall");
        builder.add(TrainMurderMysteryBlocks.CULLING_BLACK_HULL, "Culling Black Hull");
        builder.add(TrainMurderMysteryBlocks.BLACK_HULL_SHEETS, "Black Hull Sheets");
        builder.add(TrainMurderMysteryBlocks.BLACK_HULL_SHEET_STAIRS, "Black Hull Sheet Stairs");
        builder.add(TrainMurderMysteryBlocks.BLACK_HULL_SHEET_SLAB, "Black Hull Sheet Slab");
        builder.add(TrainMurderMysteryBlocks.BLACK_HULL_SHEET_WALL, "Black Hull Sheet Wall");
        builder.add(TrainMurderMysteryBlocks.MAHOGANY_PLANKS, "Mahogany Planks");
        builder.add(TrainMurderMysteryBlocks.MAHOGANY_STAIRS, "Mahogany Stairs");
        builder.add(TrainMurderMysteryBlocks.MAHOGANY_SLAB, "Mahogany Slab");
        builder.add(TrainMurderMysteryBlocks.SMOOTH_MAHOGANY, "Smooth Mahogany");
        builder.add(TrainMurderMysteryBlocks.SMOOTH_MAHOGANY_STAIRS, "Smooth Mahogany Stairs");
        builder.add(TrainMurderMysteryBlocks.SMOOTH_MAHOGANY_SLAB, "Smooth Mahogany Slab");
        builder.add(TrainMurderMysteryBlocks.MAHOGANY_PANEL, "Mahogany Panel");
        builder.add(TrainMurderMysteryBlocks.MAHOGANY_CABINET, "Mahogany Cabinet");
        builder.add(TrainMurderMysteryBlocks.MAHOGANY_BOOKSHELF, "Mahogany Bookshelf");
        builder.add(TrainMurderMysteryBlocks.MAHOGANY_HERRINGBONE, "Mahogany Herringbone");
        builder.add(TrainMurderMysteryBlocks.MAHOGANY_HERRINGBONE_STAIRS, "Mahogany Herringbone Stairs");
        builder.add(TrainMurderMysteryBlocks.MAHOGANY_HERRINGBONE_SLAB, "Mahogany Herringbone Slab");
        builder.add(TrainMurderMysteryBlocks.BUBINGA_PLANKS, "Bubinga Planks");
        builder.add(TrainMurderMysteryBlocks.BUBINGA_STAIRS, "Bubinga Stairs");
        builder.add(TrainMurderMysteryBlocks.BUBINGA_SLAB, "Bubinga Slab");
        builder.add(TrainMurderMysteryBlocks.BUBINGA_PANEL, "Bubinga Panel");
        builder.add(TrainMurderMysteryBlocks.BUBINGA_CABINET, "Bubinga Cabinet");
        builder.add(TrainMurderMysteryBlocks.BUBINGA_BOOKSHELF, "Bubinga Bookshelf");
        builder.add(TrainMurderMysteryBlocks.BUBINGA_HERRINGBONE, "Bubinga Herringbone");
        builder.add(TrainMurderMysteryBlocks.BUBINGA_HERRINGBONE_STAIRS, "Bubinga Herringbone Stairs");
        builder.add(TrainMurderMysteryBlocks.BUBINGA_HERRINGBONE_SLAB, "Bubinga Herringbone Slab");
        builder.add(TrainMurderMysteryBlocks.SMOOTH_BUBINGA, "Smooth Bubinga");
        builder.add(TrainMurderMysteryBlocks.SMOOTH_BUBINGA_STAIRS, "Smooth Bubinga Stairs");
        builder.add(TrainMurderMysteryBlocks.SMOOTH_BUBINGA_SLAB, "Smooth Bubinga Slab");
        builder.add(TrainMurderMysteryBlocks.EBONY_PLANKS, "Ebony Planks");
        builder.add(TrainMurderMysteryBlocks.EBONY_STAIRS, "Ebony Stairs");
        builder.add(TrainMurderMysteryBlocks.EBONY_SLAB, "Ebony Slab");
        builder.add(TrainMurderMysteryBlocks.EBONY_HERRINGBONE, "Ebony Herringbone");
        builder.add(TrainMurderMysteryBlocks.EBONY_HERRINGBONE_STAIRS, "Ebony Herringbone Stairs");
        builder.add(TrainMurderMysteryBlocks.EBONY_HERRINGBONE_SLAB, "Ebony Herringbone Slab");
        builder.add(TrainMurderMysteryBlocks.SMOOTH_EBONY, "Smooth Ebony");
        builder.add(TrainMurderMysteryBlocks.SMOOTH_EBONY_STAIRS, "Smooth Ebony Stairs");
        builder.add(TrainMurderMysteryBlocks.SMOOTH_EBONY_SLAB, "Smooth Ebony Slab");
        builder.add(TrainMurderMysteryBlocks.EBONY_PANEL, "Ebony Panel");
        builder.add(TrainMurderMysteryBlocks.EBONY_CABINET, "Ebony Cabinet");
        builder.add(TrainMurderMysteryBlocks.TRIMMED_EBONY_STAIRS, "Trimmed Ebony Stairs");
        builder.add(TrainMurderMysteryBlocks.EBONY_BOOKSHELF, "Ebony Bookshelf");
        builder.add(TrainMurderMysteryBlocks.OAK_BRANCH, "Oak Branch");
        builder.add(TrainMurderMysteryBlocks.SPRUCE_BRANCH, "Spruce Branch");
        builder.add(TrainMurderMysteryBlocks.BIRCH_BRANCH, "Birch Branch");
        builder.add(TrainMurderMysteryBlocks.JUNGLE_BRANCH, "Jungle Branch");
        builder.add(TrainMurderMysteryBlocks.ACACIA_BRANCH, "Acacia Branch");
        builder.add(TrainMurderMysteryBlocks.DARK_OAK_BRANCH, "Dark Oak Branch");
        builder.add(TrainMurderMysteryBlocks.MANGROVE_BRANCH, "Mangrove Branch");
        builder.add(TrainMurderMysteryBlocks.CHERRY_BRANCH, "Cherry Branch");
        builder.add(TrainMurderMysteryBlocks.BAMBOO_POLE, "Bamboo Pole");
        builder.add(TrainMurderMysteryBlocks.CRIMSON_STIPE, "Crimson Stipe");
        builder.add(TrainMurderMysteryBlocks.WARPED_STIPE, "Warped Stipe");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_OAK_BRANCH, "Stripped Oak Branch");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_SPRUCE_BRANCH, "Stripped Spruce Branch");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_BIRCH_BRANCH, "Stripped Birch Branch");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_JUNGLE_BRANCH, "Stripped Jungle Branch");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_ACACIA_BRANCH, "Stripped Acacia Branch");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_DARK_OAK_BRANCH, "Stripped Dark Oak Branch");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_MANGROVE_BRANCH, "Stripped Mangrove Branch");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_CHERRY_BRANCH, "Stripped Cherry Branch");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_BAMBOO_POLE, "Stripped Bamboo Pole");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_CRIMSON_STIPE, "Stripped Crimson Stipe");
        builder.add(TrainMurderMysteryBlocks.STRIPPED_WARPED_STIPE, "Stripped Warped Stipe");
        builder.add(TrainMurderMysteryBlocks.PANEL_STRIPES, "Panel Stripes");
        builder.add(TrainMurderMysteryBlocks.TRIMMED_RAILING, "Trimmed Railing");
        builder.add(TrainMurderMysteryBlocks.CARGO_BOX, "Cargo Box");
        builder.add(TrainMurderMysteryBlocks.WHITE_LOUNGE_COUCH, "White Lounge Couch");
        builder.add(TrainMurderMysteryBlocks.WHITE_TRIMMED_BED, "White Trimmed Bed");
        builder.add(TrainMurderMysteryBlocks.RED_TRIMMED_BED, "Red Trimmed Bed");
        builder.add(TrainMurderMysteryBlocks.WHITE_OTTOMAN, "White Ottoman");
        builder.add(TrainMurderMysteryBlocks.BLUE_LOUNGE_COUCH, "Blue Lounge Couch");
        builder.add(TrainMurderMysteryBlocks.GREEN_LOUNGE_COUCH, "Green Lounge Couch");
        builder.add(TrainMurderMysteryBlocks.RED_LEATHER_COUCH, "Red Leather Couch");
        builder.add(TrainMurderMysteryBlocks.BROWN_LEATHER_COUCH, "Brown Leather Couch");
        builder.add(TrainMurderMysteryBlocks.BEIGE_LEATHER_COUCH, "Beige Leather Couch");
        builder.add(TrainMurderMysteryBlocks.COFFEE_TABLE, "Coffee Table");
        builder.add(TrainMurderMysteryBlocks.BAR_TABLE, "Bar Table");
        builder.add(TrainMurderMysteryBlocks.BAR_STOOL, "Bar Stool");
        builder.add(TrainMurderMysteryBlocks.GOLD_BAR, "Gold Bar");
        builder.add(TrainMurderMysteryBlocks.GOLD_LEDGE, "Gold Ledge");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_BAR, "Stainless Steel Bar");
        builder.add(TrainMurderMysteryBlocks.TRIMMED_LANTERN, "Trimmed Lantern");
        builder.add(TrainMurderMysteryBlocks.WALL_LAMP, "Wall Lamp");
        builder.add(TrainMurderMysteryBlocks.NEON_PILLAR, "Neon Pillar");
        builder.add(TrainMurderMysteryBlocks.NEON_TUBE, "Neon Tube");
        builder.add(TrainMurderMysteryBlocks.STAINLESS_STEEL_SPRINKLER, "Stainless Steel Sprinkler");
        builder.add(TrainMurderMysteryBlocks.GOLD_SPRINKLER, "Golden Sprinkler");
        builder.add(TrainMurderMysteryBlocks.SMALL_BUTTON, "Small Button");
        builder.add(TrainMurderMysteryBlocks.ELEVATOR_BUTTON, "Elevator Button");
        builder.add(TrainMurderMysteryBlocks.GOLD_ORNAMENT, "Golden Ornament");
        builder.add(TrainMurderMysteryBlocks.SMALL_GLASS_DOOR, "Small Glass Door");
        builder.add(TrainMurderMysteryBlocks.SMALL_WOOD_DOOR, "Small Wood Door");

        builder.add(TrainMurderMysteryItems.ROOM_KEY, "Room Key");
        builder.add(TrainMurderMysteryItems.LOCKPICK, "Lockpick");
        builder.add(TrainMurderMysteryItems.KNIFE, "Knife");
        builder.add(TrainMurderMysteryItems.REVOLVER, "Revolver");
        builder.add(TrainMurderMysteryItems.POISON_VIAL, "Poison Vial");
        builder.add(TrainMurderMysteryItems.SCORPION, "Scorpion");

        builder.add("itemGroup.trainmurdermystery.building", "TrainMurderMystery: Building Blocks");
        builder.add("itemGroup.trainmurdermystery.decoration", "TrainMurderMystery: Decoration & Functional");
        builder.add("itemGroup.trainmurdermystery.equipment", "TrainMurderMystery: Equipment");
        builder.add("category.trainmurdermystery", "Reach For The Stars");
        builder.add("key.trainmurdermystery.spaceshipRoll", "Roll Spaceship");
        builder.add("key.trainmurdermystery.spaceshipDismount", "Dismount Spaceship");
        builder.add("key.trainmurdermystery.toggleFlashlight", "Toggle Flashlight");
        builder.add("container.cargo_box", "Cargo Box");
        builder.add("container.cabinet", "Cabinet");
        builder.add("subtitles.block.cargo_box.close", "Cargo Box closes");
        builder.add("subtitles.block.cargo_box.open", "Cargo Box opens");
        builder.add("subtitles.block.door.toggle", "Door operates");

        builder.add("tip.door.requires_key", "This door is locked and requires a key to be opened.");
        builder.add("tip.door.requires_different_key", "This door is locked and requires a different key to be opened.");
    }
}
